import * as fs from 'node:fs/promises';
import * as path from 'node:path';

/** Default sidebar walk depth. Used by the CLI and by generateSidebar. */
export const DEFAULT_MAX_DEPTH = 5;

const SKIP_DIRS = new Set([
  'node_modules',
  'dist',
  'bin',
  'obj',
  'out',
  'build',
  'target',
  'coverage',
  '.next',
  '.turbo',
  '.cache',
  '__pycache__',
  '.venv',
  'venv',
  '.git',
  '.idea',
  '.vscode',
  '.vs',
  '.gradle',
  'TestResults',
]);

const SKIP_FILES = new Set(['_sidebar.md', '_navbar.md', '_coverpage.md']);

export interface SidebarOptions {
  /** Max directory nesting depth to walk. 0 means root-level files only. */
  maxDepth?: number;
}

/**
 * Generate a docsify _sidebar.md from a real docs folder.
 *
 * `urlRoot` is the URL prefix docsify needs to reach files in the docs folder.
 * With basePath '/' and the docs folder junctioned at /docs, this is 'docs'.
 *
 * Emitted links are **absolute** (start with `/`) because docsify has
 * `relativePath: true` so that in-document author links resolve sensibly.
 * That same setting would re-resolve relative sidebar links against the
 * current page (e.g. clicking 'Components' from /docs/architecture/README
 * would fetch /docs/architecture/docs/architecture/components.md), so the
 * sidebar must use absolute paths.
 *
 * Each path segment is URL-encoded so filenames with parens (e.g.
 * `(template).md`), spaces, or other special characters route correctly.
 */
export async function generateSidebar(
  docsPath: string,
  urlRoot: string = 'docs',
  opts: SidebarOptions = {}
): Promise<string> {
  const maxDepth = opts.maxDepth ?? DEFAULT_MAX_DEPTH;
  const lines: string[] = [];
  await walk(docsPath, [urlRoot], 0, maxDepth, lines, new Set());
  if (lines.length === 0) {
    return '- _(no markdown files found)_\n';
  }
  return lines.join('\n') + '\n';
}

function toUrl(parts: string[]): string {
  return '/' + parts.map(encodeSegment).join('/');
}

export function encodeSegment(s: string): string {
  // encodeURIComponent leaves () alone — fine for HTTP, but markdown's
  // link-destination grammar terminates at the first unbalanced ')'. Encode
  // parens explicitly so filenames like `(template).md` survive the markdown
  // → docsify parse step intact.
  return encodeURIComponent(s).replace(/\(/g, '%28').replace(/\)/g, '%29');
}

/**
 * Generate a synthetic homepage when the user's docs folder has no README.md.
 * Intentionally short — a placeholder, not a real welcome page.
 */
export function generateHomepage(docsPath: string): string {
  const folderName = path.basename(docsPath);
  const repoName = path.basename(path.dirname(docsPath));
  return `# ${folderName}\n\nBrowsing \`${repoName}/${folderName}\`. Use the sidebar to navigate.\n\n> This homepage was generated by mddocs because no \`README.md\` was found in your docs folder. Add a \`README.md\` to replace it.\n`;
}

async function walk(
  dir: string,
  urlParts: string[],
  depth: number,
  maxDepth: number,
  lines: string[],
  seen: Set<string>
): Promise<void> {
  const realDir = await realPathOrSelf(dir);
  if (seen.has(realDir)) return;
  seen.add(realDir);

  let entries: import('node:fs').Dirent[];
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }

  entries.sort((a, b) => {
    if (a.isDirectory() !== b.isDirectory()) return a.isDirectory() ? -1 : 1;
    return a.name.localeCompare(b.name);
  });

  const indent = '  '.repeat(depth);

  for (const e of entries) {
    if (e.name.startsWith('.')) continue;
    if (e.isDirectory()) {
      if (SKIP_DIRS.has(e.name)) continue;
      if (depth >= maxDepth) continue;
      const subdir = path.join(dir, e.name);
      if (!(await hasMarkdown(subdir, depth + 1, maxDepth))) continue;
      const subParts = [...urlParts, e.name];
      const niceName = humanize(e.name);
      const readme = path.join(subdir, 'README.md');
      if (await pathExists(readme)) {
        lines.push(`${indent}- [${niceName}](${toUrl([...subParts, 'README.md'])})`);
      } else {
        lines.push(`${indent}- ${niceName}`);
      }
      await walk(subdir, subParts, depth + 1, maxDepth, lines, seen);
    } else if (e.isFile() && e.name.toLowerCase().endsWith('.md')) {
      if (SKIP_FILES.has(e.name)) continue;
      // README at the root is the homepage; README in a subfolder was already linked above.
      if (e.name === 'README.md') continue;
      const niceName = humanize(e.name.replace(/\.md$/i, ''));
      lines.push(`${indent}- [${niceName}](${toUrl([...urlParts, e.name])})`);
    }
  }
}

async function hasMarkdown(
  dir: string,
  depth: number,
  maxDepth: number,
  seen: Set<string> = new Set()
): Promise<boolean> {
  const realDir = await realPathOrSelf(dir);
  if (seen.has(realDir)) return false;
  seen.add(realDir);

  let entries: import('node:fs').Dirent[];
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return false;
  }
  for (const e of entries) {
    if (e.name.startsWith('.')) continue;
    if (e.isFile() && e.name.toLowerCase().endsWith('.md') && !SKIP_FILES.has(e.name)) return true;
  }
  if (depth >= maxDepth) return false;
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    if (e.name.startsWith('.') || SKIP_DIRS.has(e.name)) continue;
    if (await hasMarkdown(path.join(dir, e.name), depth + 1, maxDepth, seen)) return true;
  }
  return false;
}

function humanize(name: string): string {
  return name
    .replace(/[-_]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await fs.stat(p);
    return true;
  } catch {
    return false;
  }
}

async function realPathOrSelf(p: string): Promise<string> {
  try {
    return await fs.realpath(p);
  } catch {
    return p;
  }
}
